using System;
using System.Text.RegularExpressions;

namespace HistoricElectionData.Spike.DataServices.Denormalizers
{
    // this is some of the ugliest code I've ever written... bleah
    // the problem is that there are so many weird names and addresses forms being used and reused...
    // what I tried to do here was to clean things up so it groups things better, for example matching all forms of
    // M Eminescu nr 1, Mihai Eminescu numarul 1, M. Eminescu nr. 1 or Mihai  Eminescu, num. 1
    // as one entry, but also some diacritics changing (i.e. Rimnicu -> Ramnicu)
    // this has become more and more painful, plus added a lot of compiling time, so I stopped to this point
    // and said it should be normalized after an import to the DB is done
    //
    // for future me: don't be dumb
    public static class NameExtensions
    {
        private static readonly Regex MultipleSpacesRegex = new Regex("\\s{2,}", RegexOptions.Compiled | RegexOptions.Multiline);

        public static string NormalizeName(this string name)
        {
            if (name == null)
            {
                return null;
            }

            var normalizedName = name.ToFormWithoutDiacritics();

            normalizedName = normalizedName
                .Replace("Mun.", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Municipiul ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Municipiu ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Orasul ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Oras ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gen.", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Loc.", " Localitatea ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sc.", " Scoala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Scoala Gen ", " Scoala Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Scoala Gen.", " Scoala Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sat. ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sat ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Satul ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Comuna ", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(" (Ce. 43)", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("P.ta", " Piata", StringComparison.InvariantCultureIgnoreCase)
                .Replace("P-ta", " Piata", StringComparison.InvariantCultureIgnoreCase)
                .Replace("P.P. Aron.", "Petru Pavel Aron ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Rm.", " Ramnicu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace(" .", ".")
                .Replace(".", ". ")
                .Replace(". .", ".", StringComparison.InvariantCultureIgnoreCase)
                .Replace(" ,", ",")
                .Replace(",,", "\"")
                .Replace("“", "\"")
                .Replace("’’", "\"")
                .Replace(",", ", ")
                .Replace(" :", ":")
                .Replace(":", ": ")
                .Replace(" ;", ";")
                .Replace(";", "; ")
                .Replace("  ", " ")
                .Replace("Sos.", " Soseaua", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Soseaua", " Soseaua ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Str.", " Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Str ", " Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Std.", " Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Std ", " Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Strada", " Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("S. A.", " S.A.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("S. C.", " S.C.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("F. C.", " F.C.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("S. R. L.", " S.R.L.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. A. P.", " C.A.P.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. F. R.", " C.F.R.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("S. N. I. F.", " S.N.I.F.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("S. N. T. R.", " S.N.T.R.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("A. N. I. F.", " A.N.I.F.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. M. E. P.", " I.M.E.P.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("F. F. T.", " F.F.T.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. O. S. F.", " I.O.S.F.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("R. S. R.", " R.S.R.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("U. M.", " U.M.", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B. O. R.", " Biserica Ortodoxa Romana ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B. O.", " Biserica Ortodoxa ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cult.", " Cultural ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Aleaa.", "Aleea ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Mag. Univ.", " Magazinul Universal ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cal.", " Calea ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Al. I.", " Alexandru Ioan ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Al. 1", " Aleea 1 ", StringComparison.InvariantCultureIgnoreCase)
                .Replace(" Ghe ", " Gheorghe ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ghe.", " Gheorghe ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Gh. Duca", " Ioan Gheorghe Duca ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gh.", " Gheorghe ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Al.", " Alexandru ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("SRL", " S.R.L. ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Tel.", " Telefon: ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Tel ", " Telefon: ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Tel:", " Telefon: ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Telefon ", " Telefon: ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr.", " Numarul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr ", " Numarul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Serv.", " Serviciul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Det.", " Detasamentul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("O. Bancila", " Octav Bancila ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. Climescu", " Victor Climescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. A. Rosetti", " Constantin Alexandru Rosetti ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gh. I. Bratianu", " Gheorghe Bratianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gh. Bratianu", " Gheorghe Bratianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. C. Bratianu", " Ion I.C. Bratianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ion I. C. Bratianu", " Ion I.C. Bratianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ioan C. Bratianu", " Ion I.C. Bratianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("IC Bratianu", " Ion I.C. Bratianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. D. Lazarescu", " Ion Dumitru Lazarescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. C. Lazarescu", " Ion Dumitru Lazarescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. I. Micu Clain", " Inochentie Micu Clain ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Micu Clain", " Inochentie Micu Clain ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Th. Aman", " Theodor Aman ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Th Aman", " Theodor Aman ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("T. Aman", " Theodor Aman ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. Alecsandri", " Vasile Alecsandri ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. Negri", " Costache Negri ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("D. Filipescu", " Dimitrie Filipescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("P. Barbuneanu", " Petre Barbuneanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Simionescu", " Ion Simionescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Simionescu", " Ion Simionescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. Filipescu", " Nicolae Filipescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. Balcescu", " Nicolae Balcescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. Angelescu", " Constantin Angelescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. Constantinescu", " Nicolae Constantinescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("G. D. Teutsch", " Georg Daniel Teutsch ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("M. Eminescu", " Mihai Eminescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. Goldis", " Vasile Goldis ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. Roaita", " Vasile Roaita ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Suciu", " Ioan Suciu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. Pavelcu", " Vasile Pavelcu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Fluieras", " Ioan Fluieras ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("K. Marx", " Karl Marx ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("T. Vladimirescu", " Tudor Vladimirescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. Milea", " Vasile Milea ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. Traian", " Calea Traian ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. Voda", " Cuza Voda ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. N. Cisman", " Nicolae Cisman ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. Cisman", " Nicolae Cisman ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("L. Patrascanu", " Lucretiu Patrascanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. V. Karpen", " Nicolae Vasilescu Karpen ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N V Karpen", " Nicolae Vasilescu Karpen ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. S. Sturdza", " Ioan Sandu Sturdza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I S Sturdza", " Ioan Sandu Sturdza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ioan S. Sturdza", " Ioan Sandu Sturdza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ioan S Sturdza", " Ioan Sandu Sturdza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ionita S. Sturdza", " Ioan Sandu Sturdza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ionita S Sturdza", " Ioan Sandu Sturdza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Alexandru Anghelus", " Alexandru Ion Anghelus ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Alex.", " Alexandru ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("A. I. Cuza", " Alexandru Ioan Cuza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("M. Viteazu", " Nihai Viteazu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Al. I. Cuza", " Alexandru Ioan Cuza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Alexandru I. Cuza", " Alexandru Ioan Cuza ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("G. Toparceanu", " George Toparceanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("J. G. Tajovsky", " Jozef Gregory Tajovsky ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Georgeta M. Cancicov", " Georgeta Mircea Cancicov ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Georgeta M Cancicov", " Georgeta Mircea Cancicov ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Georgeta Cancicov", " Georgeta Mircea Cancicov ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. I. Lenin", " Vladimir Ilici Lenin ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("D. Radulescu", " Dumitru Radulescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. Halauceanu", " Ion Halauceanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("H. M. Berthelot", " Henri Mathias Berthelot ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. V. Miciurin", " Ivan Vladimirovich Michurin ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Florian Ulmeanu", " Florian C. Ulmeanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Fl. C. Ulmeanu", " Florian C. Ulmeanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Fl C Ulmeanu", " Florian C. Ulmeanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Florian C Ulmeanu", " Florian C. Ulmeanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ioana R. Rosetti", " Ioana Radu Rosetti ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ioana R Rosetti", " Ioana Radu Rosetti ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Fl. Ulmeanu", " Florian C. Ulmeanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("A. Cazaban", " Alexandru Cazaban ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. C. Baicoianu", " Constantin I. Baicoianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Constantin I Baicoianu", " Constantin I. Baicoianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Constantin Baicoianu", " Constantin I. Baicoianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ion Baicoianu", " Constantin I. Baicoianu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("M. Constantinescu", " Miron Constantinescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. Constantinescu", " Constantin Constantinescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("G. K. Constantinescu", " George Constantinescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("A. M. Guttenbrunn", " Adam Muller Guttenbrunn ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("V. V. Stanciu", " Vasile V. Stanciu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Stanciu V. V. ", " Vasile V. Stanciu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. Roznovanu", " Nicolae Roznovanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("A. Muresanu", " Andrei Muresanu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("S. Tekelja", " Sava Tekelja ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("N. Dascalescu", " Nicolae Dascalescu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Tartaria.", " Tartaria ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("St. O. Iosif", " Stefan Octavian Iosif ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. L. Caragiale", " Ion Luca Caragiale ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Mag.Feroemail", " Magazinul Feroemail ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B. P. Hasdeu", " Bogdan Petriceicu Hasdeu ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Soc. Agr. Fratila", " Societatii Agricole Fratila ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Prof.", " Profesor", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Soc. Agr. Opatita", " Societatii Agricole Opatita ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Of. Postal", " Oficiul Postal ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Lic.", " Liceul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Scol.", " Scolar ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gen.", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ind.", " Industrial ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Imp.", " Imparatul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Indep.", " Independentei ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Spl.", " Splaiul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Rep.", " Republica ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ep.", " Episcop ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Grad.", " Gradinita ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Progr.", " Program ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Prof.", " Profesor ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Strinv.", " Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Inv.", " Invatator ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("?Nv.", " Invatator ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Dr.", " Doctor ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sold.", " Soldat ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gr.", " Grupul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("G-ral", " General ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Med.", " Medical ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col. Th.", " Colegiul Tehnic ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col. Tehnic", " Colegiul Tehnic ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col. Egiul", " Colegiul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col. Nat.", " Colegiul National ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col. National", " Colegiul National ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col. Agricol", " Colegiul Agricol ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Colegiul Tehnic.", " Colegiul Tehnic ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Dtru.", " Dumitru ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("D-tru.", " Dumitru ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ped.", " Pedagogic ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sed.", " Sedinte ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sublt.", " Sublocotenent ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Slt.", " Sublocotenent ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Col.", " Colonel ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Lt.", " Locotenent ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sg.", " Sergent ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sg .", " Sergent ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Intr.", " Intrarea ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ing.", " Inginer ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B-dul.", " Bulevardul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Bd.", " Bulevardul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B. dul", " Bulevardul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B.dul", " Bulevardul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Bd ", " Bulevardul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cls.", " Clasele ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cls i-", " Clasele ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cls i -", " Clasele ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cls ", " Clasa ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Rec.", " Recreere ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Dec.", " Decembrie ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Oct.", " Octombrie ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Insp.", " Inspectoratul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Disp.", " Dispensarul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Dir. ", " Directiei ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Leresti. ", " Leresti, ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Directiei Jud.", " Directiei Judetene ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Gradinita Pp", " Gradinita Cu Program Prelungit ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Asociatia Propr.", " Asociatia Proprietari ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Propr. Privata", " Proprietate Privata ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Propr.", " Proprietatea ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Normal", " Program Normal ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Norm.", " Program Normal ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Prelungit", " Program Prelungit ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Tatarilor", " Preluca Tatarilor ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Carjei", " Paraul Carjei ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Pintei", " Paraul Pintei ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Prel.", " Program Prelungit ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr. Doctor", " Profesot Doctor ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pr.", " Preot ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Bibl. Jud.", " Biblioteca Judeteana ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Fil.", " Filiala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Bihor", " Judetul Bihor ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Iasi", " Judetul Iasi ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Drm Jud.", " Drumul Judetean ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Suceava", " Judetul Suceava ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Alba", " Judetul Alba ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Ph", " Judetul Prahova ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Prahova", " Judetul Prahova ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud. Suce", " Judetul Suceava ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Jud.", " Judetean ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pol.", " Politiei ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Detransp.", " De Transporturi ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Transp.", " Transporturi ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sala Sp.", " Sala Sporturilor ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sp.", " Spitalul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Grupul Ec.", " Grupul Economic ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cons.", " Consiliere ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ec.", " Ecaterina ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Bdul.", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("B-dul", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Bdul", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Blvd.", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Blv.", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Blvd", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Blv", " Bulevardul", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Soc.", " Societatea", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Agr.", " Agricola", StringComparison.InvariantCultureIgnoreCase)
                .Replace("As.", " Asociatia", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Av.", " Aviator ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cpt. Av", " Capitan Aviator ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cpt Av", " Capitan Aviator ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cpt.", " Capitan ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cap.", " Capitan ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cp:", " Codul Postal ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cp.", " Codul Postal ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Vet.", " Veterinar", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. Oradea", " Universitatea Oradea", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. '", " Universitatea '", StringComparison.InvariantCultureIgnoreCase)
                .Replace("A. Vlaicu", "Aurel Vlaicu", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. Aurel", " Universitatea Aurel", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. Lucian", " Universitatea Lucian", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. Pro", " Universitatea Pro", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. De ", " Universitatea De ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. Stiinte", " Universitatea De Stiinte", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ. Tehnica", " Universitatea Tehnica", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Univ.", " Universitar", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Colegiul Universitatea", " Colegiul Universitar", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Agronom.", " Agronomice", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sala sedinte", " Sala De Sedinte", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ed.", " Educatie", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Centr. De Transf.", " Centrului De Transfuzii ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Tg.", " Targu", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Bl.", " Bloc ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Et.", " Etaj ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cicoarea Sf. Daniel", " Cicoarea Sfantului Daniel ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Treime", " Sfanta Treime ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Lucia", " Sfanta Lucia ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Cel Mare Si Sfant", " Stefan Cel Mare Si Sfant ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Elena", " Sfanta Elena ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Maria", " Sfanta Maria ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Fecioara", " Sfanta Fecioara ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Constantin Si Elena", " Sfintii Constantin Si Elena ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Arhangheli", " Sfintii Arhangheli ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Arh. Mihail Si Gavril", " Sfintii Arhangheli Mihail Si Gavril ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Imparati", " Sfintii Imparati ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf. Ecaterina", " Sfanta Ecaterina ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sf.", " Sfantul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Arh .", " Arhitect ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Ap.", " Apartament ", StringComparison.InvariantCultureIgnoreCase).Replace("Etaj.", " Etaj ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Primaria Com.", " Primaria Comunei ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Com.", " Comuna ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Scpcb", "S.C.P.C.B. ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cl. ", " Clasele ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("I. - I", " I - I", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I - Iv-", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I - Iv-", " Primara ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I - Iv", " Generala", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I - Iv", " Primara", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I-Iv-", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I-Iv-", " Primara ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I-Iv", " Generala", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I-Iv", " Primara", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I-Viii-", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I-Viii-", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I-Viii", " Generala", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I-Viii", " Generala", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I - Viii-", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I - Viii-", " Generala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Generala Cu Clasele I - Viii", " Generala", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I - Xii", "", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele I-Xii", "", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele Ix - Xii", "", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cu Clasele Ix-Xii", "", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Mixt-", " Mixt, ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sala-", " Sala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sala.", " Sala ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Izv.", " Izvorul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Num.", " Numarul ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Acad.", " Academician ", StringComparison.InvariantCultureIgnoreCase)
                .Replace(" - ", ", ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("-,", ",", StringComparison.InvariantCultureIgnoreCase)
                .Replace(". :", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Strada .", "Strada ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("C. L.", " Consiliului Local ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Iv.", "Iv,", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr0", "Numarul 0", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr1", "Numarul 1", StringComparison.InvariantCultureIgnoreCase)
                .Replace("1.", "1", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr2", "Numarul 2", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr3", "Numarul 3", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr4", "Numarul 4", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr5", "Numarul 5", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr6", "Numarul 6", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr7", "Numarul 7", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Telefon: 2", " Telefon: 02", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Telefon:  2", " Telefon: 02", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr8", "Numarul 8", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Nr9", "Numarul 9", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Festivittai", " Festivitati", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Grup Scolar De", " Grupul Scolar De ", StringComparison.InvariantCultureIgnoreCase)
                .Replace("( ", "(", StringComparison.InvariantCultureIgnoreCase)
                .Replace(" )", ")", StringComparison.InvariantCultureIgnoreCase)
                .Replace(", Numarul F. Numarul", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(" Numarul F. Numarul", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(", Numarul F. N.", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(" Numarul F. N.", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(", Numarul F. N", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(" Numarul F. N", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(", Numarul FN.", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(" Numarul FN.", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(", Numarul FN", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace(" Numarul FN", string.Empty, StringComparison.InvariantCultureIgnoreCase)
                .Replace("Strainatate", "Diaspora", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sinpetru", "Sanpetru", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Piriu", "Parau", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Pirjol", "Parjol", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sfint", "Sfant", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sfanti", "Sfinti", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cirta", "Carta", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Topirceanu", "Toparceanu", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cirtisoara", "Cartisoara", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cirjei", "Carjei", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Vilcea", "Valcea", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Dimbov", "Dambov", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Girbov", "Garbov", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cimpen", "Campen", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Vintu", "Vantu", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Cimpu", "Campu", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sinti", "Santi", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sinta", "Santa", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Sfint", "Sfant", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Rimnic", "Ramnic", StringComparison.InvariantCultureIgnoreCase)
                .Replace("Hargita", "Harghita", StringComparison.InvariantCultureIgnoreCase);

            return MultipleSpacesRegex.Replace(normalizedName, " ").Trim();
        }
    }
}
